<template>
  <q-page class="flex flex-center">
    Your age is {{ this.$store.state.profile.age }}
    <q-btn
          color="secondary"
          style="width:200px;"
          @click="$router.push('/')"
          >Selete Age</q-btn>
      <div id="body-container">
        <!-- Image Map Generated by http://www.image-map.net/ -->
        <img usemap="#image-map" style="height:599px;width:264px;">
        <map name="image-map">
          <area target="" alt="neck" title="neck" href="#" coords="107,68,114,94,152,96,157,68" shape="poly">
          <area target="" alt="head" title="head" href="#" coords="132,34,31" shape="circle">
          <area target="" alt="leg" title="leg" @click="$router.push('/legparts')" coords="139,343,190,341,186,386,180,401,181,418,184,431,186,448,188,463,189,477,188,491,187,505,186,534,196,562,205,585,182,598" shape="poly">
        </map>
      </div>
  </q-page>
</template>

<script>
export default {
  // name: 'PageName',
  name: 'BodyPart'
}
</script>

<style>
area {
 color:rgba(255,255,255,0.5);
 z-index: 1;
}

#body-container{
  background-image:url("/statics/body.png");
  height:599px;
  width:264px;
}
</style>
